# Generated by Django 5.2.11 on 2026-02-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionstep',
            name='log',
            field=models.JSONField(blank=True, help_text='Step log: transcript, image_descriptions, llm_raw.', null=True),
        ),
    ]
